---
title: "Tutorial: Basic Classfication"
output: html_notebook
date: 06-10-2019
---

https://keras.rstudio.com/articles/tutorial_basic_classification.html

## Installation
```{r}
devtools::install_github("rstudio/keras")
devtools::install_github("rstudio/tensorflow")

# backend use TensorFlow
library(keras)

# conda install python==3.7
install_keras()
library("tensorflow")
install_tensorflow(version = "nightly")
#install_keras(method = "conda")
```

## Preparing the Data

`module load java`

```{r}
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
```

```{r}
# reshape
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))
# rescale
x_train <- x_train / 255
x_test <- x_test / 255
```



```{r}
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)
```


```{r}
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')

summary(model)
```

```{r}
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
```



```{r}
history <- model %>% fit(
  x_train, y_train, 
  epochs = 30, batch_size = 128, 
  validation_split = 0.2
)
```


```{r}
plot(history)
```






